config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root'pages#home'
  get '/about', to: 'pages#about'

  resources :articles


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true,
                       length: { minimum: 3, maximum: 25 },
                       uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum:100 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :set_article, only: [:edit, :show, :update, :destroy]

  def new
      @article = Article.new
  end

  def edit
  end

  def index
    @articles = Article.all
  end

  def create
      #render plain: params[:article].inspect
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'new'
    end

  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = 'The Article was deleted'

    redirect_to articles_path
  end


  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

def about
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="container">
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class='form-group'>
      <div class='control-label col-sm-2'>
        <%=f.label :title%>
      </div>
      <div class='col-sm-8'>
        <%=f.text_field :title, class:"form-control", placeholder:"Title of the article", autofocus: true %>
      </div>
    </div>
    <div class='form-group'>
      <div class='control-label col-sm-2'>
        <%=f.label :description%>
      </div>
      <div class='col-sm-8'>
      <%=f.text_area :description, class:"form-control", placeholder:"Type the text here"%>
    </div>
    </div>
    <div class='form-group'>
      <div class='col-sm-offset-2 col-sm-10'>
        <%=f.submit class:'btn btn-primary btn-lg'%>
        <%= link_to "Cancel", articles_path, class: "btn btn-lg btn-warning" %>
      </div>
    </div>


    <div class="center">
      [ <%= link_to "Main list", articles_path %> ]
    </div>
</div>
<%end%>

app/views/articles/edit.html.erb
<h1>Article edit page. Welcome!</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles LISTING</h1>

<% @articles.each do |article| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="article-title">
        <%= link_to article.title, article_path(article) %>
      </div>
      <div class="article-body">
        <%= truncate(article.description, length:50) %>
      </div>

      <div class="article-actions">
        <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
        <%= link_to "Delete this article", article_path(article), method: :delete,
                                      data: { confirm: "Are you sure you want to delete the article?"},
                                      class: "btn btn-xs btn-danger" %>
      </div>
    </div>
  </div>
</div>
    
<%end%>

app/views/articles/new.html.erb
<h1>Create new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
  <div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center description"><strong>Description:</strong></h4>
      <hr>
        <%= simple_format(@article.description) %>
        <div class="article-actions">
          <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(@article), method: :delete,
                                              data: { confirm: "Are you sure you want to delete the article?"},
                                              class: "btn btn-xs btn-danger" %>
          <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
        </div>

  </div>

app/views/layouts/_footer.html.erb
<div class='container'>
    <footer class='footer'>
      <small>
        This is study project of Aleksey Gladkov
      </small>
      <ul>
        <li><%= link_to 'About', about_path %></li>
      </ul>
        

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" id="logo" href="#">AVG AlphaBlog</a> -->
      <%= link_to 'AVG AlphaBlog', root_path, class:"navbar-brand", id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to "Articles Listing", articles_path %> </li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!-- <li><a href="#">Add New Article</a></li> -->
            <li><%= link_to "Add new Article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <div class='container'>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<style>
  body {
		text-align: left;
		color: #998057;
    padding: 20px;
  		}
	h1 {
		font-family: Consolas;
		color: #998057;
		font-size: 150%;
    padding: 20px;
		}
	p {
		font-family: sans-serif;
		color: #998057;
		font-size: 110%;
    }
	header {
		text-align: center;
		font-size: 140%;
    background-color: #cebc96;
    padding: 5px;
		}
  address {
      color: #cebc96;
      padding: 20px;
    }
    hr {
      color: #6d8dc0;
    }
</style>

<header>
<h1>About</h1>
<hr>
</header>

<body>
<p>This page is created for educational purposes</p>
<p>I'm planning to develope this page further according to course plan</p>
</body>

<footer>
<hr>
<adress>
Welcome to  visit the main page!<br>
follow the <%= link_to 'Link', root_path %>!
</adress>
</footer>

</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<div class="center jumbotron">
  <h1>Welcome to my AlphaBlog!</h1>
  <%= link_to "Sign-up!", "#", class:"btn btn-primary btn-xlarge" %>

</div>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
            The following
            <%= pluralize(obj.errors.count, "error") %>
            prevented the article from getting created:
        </h2>
        <div class="panel-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>